version: '3'

services:
  app:
    image: "farhansajid2/django-k8s-app"


    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
      - GOOGLE_PASSWORD=${GOOGLE_PASSWORD}
      - GOOGLE_USER=${GOOGLE_USER}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - DJANGO_SETTINGS_MODULE=django_project.settings.production # production environment
      - USE_S3=TRUE
      - SECRET_KEY='afoiajsfoija84284uijskflkamlfkmaskfjaofjoa'
      - REDIS_HOST=redis
    links:
      - postgres

    command: gunicorn -w 4 -b 0.0.0.0:8990 --env DJANGO_SETTINGS_MODULE=django_project.settings.production django_project.wsgi

  redis:
    image: 'redis'

  postgres:
    image: 'postgres'

  nginx:
    restart: always
    image: "farhansajid2/django-nginx"
    ports:
      - "9000:80"
    depends_on:
      - app
